Blocker:
    - 'Urgent'
Issue:
    - 'High'
High-Risk:
    - 'Medium'
Low-Risk:
    - 'Low'
Core:
    - 'Core'
Merchant Services:
    - 'Merchant Services'
Corporate Data:
    - 'Corporate Data'
Commercial Data:
    - 'Commercial Data'
Infrastructure:
    - 'Infrastructure'
Analytics Engineering:
    - 'Analytics Engineering'
Other:
    - 'Other'
EscalateTo-AreaChampion:
    - 'Area Champion'
EscalateTo-Director:
    - 'Area/Team Director'
EscalateTo-AE:
    - 'AE (Analytics Engineering)'
EscalateTo-SDP:
    - 'SDP Team (DPE)'
EscalateTo-Nell:
    - 'Nell Thomas'
