Blocker:
    - 'Urgent'
Issue:
    - 'High'
High-Risk:
    - 'Medium'
Low-Risk:
    - 'Low'
Core:
    - 'Core'
Merchant Services:
    - 'Merchant Services'
Corporate Data:
    - 'Corporate Data'
Commercial Data:
    - 'Commercial Data'
Analytics Engineering:
    - 'Analytics Engineering'
Infrastructure:
    - 'Infrastructure'
Area Champion:
    - 'Area Champion'
Director:
    - 'Area/Team Director'
AE:
    - 'Analytics Engineering'
SDP:
    - 'SDP Team (DPE)'
Nell:
    - 'Nell Thomas'
