---
name: Epic
description: Requirements, considerations, definition of done for a feature
title: "[Epic] "
labels:
  - Epic
assignees: []
body:
  - type: input
    id: summary
    attributes:
      label: Concise summary of feature to be delivered
    validations:
      required: true
  - type: input
    id: design
    attributes:
      label: Design link
      value: "[Designs]()"
    validations:
      required: true
  - type: textarea
    id: brd
    attributes:
      label: BRD / Stories
      description: List all the business requirements / stories associated with this
        Epic and Design
      placeholder: List 1, 2, 3...
    validations:
      required: false
  - type: textarea
    id: open-questions
    attributes:
      label: Open Questions
      description: List open questions, definition of done or any other details here
      value: |

        _Engineering to click on the _Add Tasklist_ button below and add tasks to complete this epic_
