- name: Add To GitHub projects
  uses: actions/add-to-project@v0.4.1
name: Issues to Projects
on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          #target a project in the organization
          #to the issue
          #project-url: https://github.com/orgs/<orgName>/projects/<projectNumber>
          project-url: https://github.com/users/asharda2022/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: "#gsd:25329"
          label-operator: OR
     
