# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types:
      - opened
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  label_issue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # permissions
    permissions:
      issues: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/github-script@v6
     with:
      script: |
        github.rest.issues.addLabels({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          labels: ["good workflow label","MyProject"]
        })
