name: Update Custom Priority in Project Based on Multiple Labels

on:
  issues:
    types:
      - labeled
      - unlabeled

jobs:
  update_custom_priority:
    runs-on: ubuntu-latest

    steps:
    - name: Update Custom Priority
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const projectId = "2";
          const relationId = "Priority";
          const issueId = context.issue.number;

          async function updatePriority() {
            const issue = await github.rest.issues.get({
              owner,
              repo,
              issue_number: issueId
            });

            const priorityLabels = {
              "Low-Priority": "Low",
              "Medium-Priority": "Medium",
              "High-Priority": "High"
            };

            let newPriority;
            issue.data.labels.forEach((label) => {
              if (priorityLabels.hasOwnProperty(label.name)) {
                newPriority = priorityLabels[label.name];
              }
            });

            if (!newPriority) {
              console.log('No matching priority label found, skipping update');
              return;
            }

            const project = await github.request(`GET /projects/{project_id}`, {
              project_id: projectId,
              headers: {
                'User-Agent': 'GitHub Actions',
                'Accept': 'application/vnd.github+json'
              }
            });

            const issueCard = await github.request(`GET /repos/{owner}/{repo}/issues/{issue_number}/project_cards`, {
              owner,
              repo,
              issue_number: issueId,
              headers: {
                'User-Agent': 'GitHub Actions',
                'Accept': 'application/vnd.github.inertia-preview+json'
              }
            });

            if (issueCard.data.length === 0) {
              console.log('Issue is not linked to any project card, skipping update');
              return;
            }

            await github.request(`PUT /projects/columns/cards/{card_id}/fields/{relation_id}`, {
              card_id: issueCard.data[0].id,
              relation_id: relationId,
              value: newPriority,
              headers: {
                'User-Agent': 'GitHub Actions',
                'Accept': 'application/vnd.github+json'
              }
            });
          }

          updatePriority();
