on:
  issues:
    types: [labeled]

jobs:
  change-attribute:
    runs-on: ubuntu-latest
    steps:
      - name: Update custom attribute value
        if: ${{ contains(github.event.issue.labels.*.name, 'Low-Priority') }}
        run:
          project-url: https://github.com/users/asharda2022/projects/2
          column-name: ToDo
          custom-attributes: |
            [{"name": "Priority", "value": "Low"}]
