name: Update Custom Priority in Project

on:
  issues:
    types:
      - labeled
      - unlabeled

jobs:
  update_custom_priority:
    runs-on: ubuntu-latest

    steps:
    - name: Update Custom Priority
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { context, github } = require('@actions/github');
          const issueLabelName = context.payload.label.name;
          const { owner, repo } = context.repo;
          const projectId = "2";
          const relationId = "Priority";
          const issueId = context.issue.number;
          
          let newPriority;
          const priorities = {
            "Low-Priority": "Low",
            "Medium-Priority": "Medium",
            "High-Priority": "High"
          };
    
          if (priorities.hasOwnProperty(issueLabelName)) {
            newPriority = priorities[issueLabelName];
          } else {
            console.log('No matching label found, skipping update');
            return;
          }
    
          async function updatePriority() {
            const project = await github.request(`GET /projects/{project_id}`, {
              project_id: projectId,
              headers: {
                'User-Agent': 'GitHub Actions',
                'Accept': 'application/vnd.github+json'
              }
            });
    
            const issueCard = await github.request(`GET /repos/{owner}/{repo}/issues/{issue_number}/project_cards`, {
              owner,
              repo,
              issue_number: issueId,
              headers: {
                'User-Agent': 'GitHub Actions',
                'Accept': 'application/vnd.github.inertia-preview+json'
              }
            });

            if (issueCard.data.length === 0) {
              console.log('Issue is not linked to any project card, skipping update');
              return;
            }

            await github.request(`GET /projects/columns/cards/{card_id}/fields/{relation_id}`, {
              card_id: issueCard.data[0].id,
              relation_id: relationId,
              value: newPriority,
              headers: {
                'User-Agent': 'GitHub Actions',
                'Accept': 'application/vnd.github+json'
              }
            });
          }
          
          updatePriority();
