name: Update Custom Priority in Project Based on Multiple Labels

on:
  issues:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  update_custom_priority:
    runs-on: ubuntu-latest

    steps:
      - name: Install octokit request
        run: npm install @octokit/request
