name: Fetch Project Info on Issue Created

on:
  issues:
    types:
      - opened

jobs:
  fetch_project_info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install @octokit/request
      run: npm install @octokit/request

    - name: Fetch project info
      run: node project-info.js
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        PROJECT_ID: 4
