name: Fetch Project Info on Issue Created

on:
  issues:
    types:
      - opened

jobs:
  fetch_project_info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch project info
      id: fetch_project_info
      uses: octokit/request-action@v2.x
      with:
        route: GET /projects/:project_id
        project_id: 4
        mediaType: '{"accept": "application/vnd.github+json"}'
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

    - name: Display project info
      run: |
        echo "Project Info:"
        echo "${{ steps.fetch_project_info.outputs.data }}"
